// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/index.tsx";
import * as $$0 from "./islands/AboutPage.tsx";
import * as $$1 from "./islands/Carousel.tsx";
import * as $$2 from "./islands/ColorMode.tsx";
import * as $$3 from "./islands/FloatingBox.tsx";
import * as $$4 from "./islands/Header.tsx";
import * as $$5 from "./islands/Menu.tsx";
import * as $$6 from "./islands/ResumeButton.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/index.tsx": $1,
  },
  islands: {
    "./islands/AboutPage.tsx": $$0,
    "./islands/Carousel.tsx": $$1,
    "./islands/ColorMode.tsx": $$2,
    "./islands/FloatingBox.tsx": $$3,
    "./islands/Header.tsx": $$4,
    "./islands/Menu.tsx": $$5,
    "./islands/ResumeButton.tsx": $$6,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
